/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author HREF DIGITAL
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btn_AñadirUsuario = new javax.swing.JButton();
        userElimination = new javax.swing.JButton();
        btnModUsuario = new javax.swing.JButton();
        btn_verUsers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_AñadirEjercicio = new javax.swing.JButton();
        ejercicioElimination = new javax.swing.JButton();
        btnModificarEjercicios = new javax.swing.JButton();
        btn_verEjercicios = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_AñadirRutina = new javax.swing.JButton();
        rutinaElimination = new javax.swing.JButton();
        btnModificarRutinas = new javax.swing.JButton();
        btn_verRutinas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_RutinaUsuario = new javax.swing.JButton();
        rutinaUsuarioElimination = new javax.swing.JButton();
        btnModificarRutinaEjecucion = new javax.swing.JButton();
        btn_verRutinaUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 250));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btn_AñadirUsuario.setText("Añadir");
        btn_AñadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AñadirUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel1.add(btn_AñadirUsuario, gridBagConstraints);

        userElimination.setText("Eliminar");
        userElimination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEliminationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel1.add(userElimination, gridBagConstraints);

        btnModUsuario.setText("Modificar");
        btnModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel1.add(btnModUsuario, gridBagConstraints);

        btn_verUsers.setText("Ver");
        btn_verUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verUsersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel1.add(btn_verUsers, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicios"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btn_AñadirEjercicio.setText("Añadir");
        btn_AñadirEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AñadirEjercicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel2.add(btn_AñadirEjercicio, gridBagConstraints);

        ejercicioElimination.setText("Eliminar");
        ejercicioElimination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicioEliminationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel2.add(ejercicioElimination, gridBagConstraints);

        btnModificarEjercicios.setText("Modificar");
        btnModificarEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEjerciciosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel2.add(btnModificarEjercicios, gridBagConstraints);

        btn_verEjercicios.setText("Ver");
        btn_verEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verEjerciciosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel2.add(btn_verEjercicios, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rutinas"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btn_AñadirRutina.setText("Añadir");
        btn_AñadirRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AñadirRutinaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel3.add(btn_AñadirRutina, gridBagConstraints);

        rutinaElimination.setText("Eliminar");
        rutinaElimination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutinaEliminationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel3.add(rutinaElimination, gridBagConstraints);

        btnModificarRutinas.setText("Modificar");
        btnModificarRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRutinasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel3.add(btnModificarRutinas, gridBagConstraints);

        btn_verRutinas.setText("Ver");
        btn_verRutinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verRutinasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel3.add(btn_verRutinas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Rutina-Usuario"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btn_RutinaUsuario.setText("Añadir");
        btn_RutinaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RutinaUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel5.add(btn_RutinaUsuario, gridBagConstraints);

        rutinaUsuarioElimination.setText("Eliminar");
        rutinaUsuarioElimination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutinaUsuarioEliminationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel5.add(rutinaUsuarioElimination, gridBagConstraints);

        btnModificarRutinaEjecucion.setText("Modificar");
        btnModificarRutinaEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRutinaEjecucionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel5.add(btnModificarRutinaEjecucion, gridBagConstraints);

        btn_verRutinaUsuario.setText("Ver");
        btn_verRutinaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verRutinaUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        jPanel5.add(btn_verRutinaUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel5, gridBagConstraints);

        jMenu1.setText("Help");

        jMenuItem1.setText("Ayuda");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userEliminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEliminationActionPerformed
        // TODO add your handling code here:
        EliminacionUsuario eliminacion = new EliminacionUsuario();
        eliminacion.setVisible(true);
        
    }//GEN-LAST:event_userEliminationActionPerformed

    private void ejercicioEliminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejercicioEliminationActionPerformed
        // TODO add your handling code here:
        EliminacionEjercicio eliminacion=new EliminacionEjercicio();
        eliminacion.setVisible(true);
    }//GEN-LAST:event_ejercicioEliminationActionPerformed

    private void rutinaEliminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutinaEliminationActionPerformed
        // TODO add your handling code here:
        EliminacionRutina eliminacion=new EliminacionRutina();
        eliminacion.setVisible(true);
    }//GEN-LAST:event_rutinaEliminationActionPerformed

    private void rutinaUsuarioEliminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutinaUsuarioEliminationActionPerformed
        // TODO add your handling code here:
        EliminacionRutinaEjecucion eliminacion=new EliminacionRutinaEjecucion();
        eliminacion.setVisible(true);
    }//GEN-LAST:event_rutinaUsuarioEliminationActionPerformed

    private void btn_verUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verUsersActionPerformed
        // TODO add your handling code here:
        VerUsuarios ver= new VerUsuarios();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_verUsersActionPerformed

    private void btn_verEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verEjerciciosActionPerformed
        // TODO add your handling code here:
        VerEjercicios ver=new VerEjercicios();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_verEjerciciosActionPerformed

    private void btn_verRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verRutinasActionPerformed
        // TODO add your handling code here:
        VerRutinas ver=new VerRutinas();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_verRutinasActionPerformed

    private void btn_verRutinaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verRutinaUsuarioActionPerformed
        // TODO add your handling code here:
        VerRutinasEjecucion ver=new VerRutinasEjecucion();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_verRutinaUsuarioActionPerformed

    private void btn_AñadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AñadirUsuarioActionPerformed
        // TODO add your handling code here:
        AñadirUsuario ver=new AñadirUsuario();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_AñadirUsuarioActionPerformed

    private void btn_AñadirEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AñadirEjercicioActionPerformed
        // TODO add your handling code here:
        AñadirEjercicio ver=new AñadirEjercicio();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_AñadirEjercicioActionPerformed

    private void btn_AñadirRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AñadirRutinaActionPerformed
        // TODO add your handling code here:
        AñadirRutina ver=new AñadirRutina();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_AñadirRutinaActionPerformed

    private void btn_RutinaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RutinaUsuarioActionPerformed
        // TODO add your handling code here:
        AñadirRutinaEjecuciones ver=new AñadirRutinaEjecuciones();
        ver.setVisible(true);
    }//GEN-LAST:event_btn_RutinaUsuarioActionPerformed

    private void btnModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModUsuarioActionPerformed
        // TODO add your handling code here:
        ModificarUsuario ver=new ModificarUsuario();
        ver.setVisible(true);
    }//GEN-LAST:event_btnModUsuarioActionPerformed

    private void btnModificarEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEjerciciosActionPerformed
        // TODO add your handling code here:
        ModificarEjercicio ver=new ModificarEjercicio();
        ver.setVisible(true);
    }//GEN-LAST:event_btnModificarEjerciciosActionPerformed

    private void btnModificarRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRutinasActionPerformed
        // TODO add your handling code here:
        ModificarRutinas ver=new ModificarRutinas();
        ver.setVisible(true);
    }//GEN-LAST:event_btnModificarRutinasActionPerformed

    private void btnModificarRutinaEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRutinaEjecucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarRutinaEjecucionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModUsuario;
    private javax.swing.JButton btnModificarEjercicios;
    private javax.swing.JButton btnModificarRutinaEjecucion;
    private javax.swing.JButton btnModificarRutinas;
    private javax.swing.JButton btn_AñadirEjercicio;
    private javax.swing.JButton btn_AñadirRutina;
    private javax.swing.JButton btn_AñadirUsuario;
    private javax.swing.JButton btn_RutinaUsuario;
    private javax.swing.JButton btn_verEjercicios;
    private javax.swing.JButton btn_verRutinaUsuario;
    private javax.swing.JButton btn_verRutinas;
    private javax.swing.JButton btn_verUsers;
    private javax.swing.JButton ejercicioElimination;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton rutinaElimination;
    private javax.swing.JButton rutinaUsuarioElimination;
    private javax.swing.JButton userElimination;
    // End of variables declaration//GEN-END:variables
}
